/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-PDF-Text-Extraction.h
 #	source generated by 4D Plugin Wizard
 #	Project : PDF Text Extraction
 #	author : miyako
 #	2021/11/11
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_PDF_TEXT_EXTRACTION_H
#define PLUGIN_PDF_TEXT_EXTRACTION_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"
#include "C_TEXT.h"

#include <string>
#include <list>

#include "EStatusCode.h"
#include "ObjectsBasicTypes.h"

#include "./lib/text-placements/TextPlacement.h"

#include "ErrorsAndWarnings.h"
#include "RefCountPtr.h"

#pragma mark -

void PDF_Extract_text(PA_PluginParameters params);

#endif /* PLUGIN_PDF_TEXT_EXTRACTION_H */
